version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\assefamaru\cellosaurus-api

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go get github.com/gin-gonic/gin
  - go get github.com/getsentry/raven-go
  - go get github.com/go-sql-driver/mysql
  - go version
  - go env

build_script:
  - go build -o buildOutput\myapp -i .

artifacts:
  - path: buildOutput/myapp
    name: binary

deploy:
  release: myapp-$(appveyor_build_version)
  description: 'App release.'
  provider: GitHub
  auth_token:
    secure: FW3tJ3fMncxvs58/ifSP7w+kBl9BlxvRMr9liHmnBs14ALRG8Vfyol+sNhj9u2JA
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: master
