# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2582e95a75d7f44d8f102070d7843e6ad1235817cd4ed559edefbb8e5714841dd5e47c1cf45ec48af882544e62f1b1bbb981edc7c4042face7af3ac26a9e04e7

test:
  secret_key_base: 9a5495cabf2d93e5ec611c3d0d35c04b2ab9337ab50ccf99c33c819c6760302f166e79fa1af5a55c06494e39d8fd5da41f00d4b3afc476ea14128f2ac2bbc699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
