# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92b8d5cbdadeeafa3e9758d66dc7fcb33eddcb341ee479f451eb9baea9572235fb4cc41d8585d8a9b7a5a374b21c05a90f539d8406839dc4786c56d4722b5042

test:
  secret_key_base: e97b110ac5c9ea4851b3238d0334a2f41c84e681ac2d3e7d6cf5eed94480edf20ee44d14ee2802990e0cf0a5094c785189e6132c13de5d92bd9d6100cb211b15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
